version: '2'

services:
  phonebook-mysql:
    container_name: db
    build:
      context: .
      dockerfile: ./dockerfile-mysql/Dockerfile
    restart: always

  phonebook-app:
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfile-app/Dockerfile
    depends_on:
      - phonebook-mysql
    ports:
      - "8181:8181"
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
        - 10000:8080